# Project

This notebook converts existing `artifacts/infer/**/final.cs` files into tabular alignment artifacts: `model_index.csv`, `elements.csv`, `column_maps`, and projection CSVs for `property`, `type`, and `relation` layers.

In [1]:
import pandas as pd
from IPython.display import JSON, display

from src.lib.align_pipeline import (
    load_column_map,
    load_projection_csv,
    prepare_project_artifacts,
)
from src.lib.infer_pipeline import find_repo_root

pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
repo_root = find_repo_root()

In [2]:
project_summary, model_index, elements = prepare_project_artifacts(repo_root)
display(JSON(project_summary, expanded=True))
display(model_index.head(10))
display(elements.head(20))

,model_id,source_document_id,condition,producer_id,document,document_stem,scenario,model,run,path,final_cs_path,metadata_path,source_matrix_line,parse_error_count,parse_errors,analysis_error
0,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs.md,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,1,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/record.json,1,0,[],None
1,framework-laptop-13-specs__control__meta-llama-llama-3-2-3b-instruct__run1,framework-laptop-13-specs,control,meta-llama/llama-3.2-3b-instruct,framework-laptop-13-specs.md,framework-laptop-13-specs,control,meta-llama/llama-3.2-3b-instruct,1,artifacts/infer/framework-laptop-13-specs/control/meta-llama-llama-3-2-3b-instruct/run1/final.cs,artifacts/infer/framework-laptop-13-specs/control/meta-llama-llama-3-2-3b-instruct/run1/final.cs,artifacts/infer/framework-laptop-13-specs/control/meta-llama-llama-3-2-3b-instruct/run1/record.json,7,0,[],None
2,framework-laptop-13-specs__control__mistralai-ministral-3b-2512__run1,framework-laptop-13-specs,control,mistralai/ministral-3b-2512,framework-laptop-13-specs.md,framework-laptop-13-specs,control,mistralai/ministral-3b-2512,1,artifacts/infer/framework-laptop-13-specs/control/mistralai-ministral-3b-2512/run1/final.cs,artifacts/infer/framework-laptop-13-specs/control/mistralai-ministral-3b-2512/run1/final.cs,artifacts/infer/framework-laptop-13-specs/control/mistralai-ministral-3b-2512/run1/record.json,13,0,[],None
3,framework-laptop-13-specs__feedback__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,feedback,google/gemini-2.5-flash-lite,framework-laptop-13-specs.md,framework-laptop-13-specs,feedback,google/gemini-2.5-flash-lite,1,artifacts/infer/framework-laptop-13-specs/feedback/google-gemini-2-5-flash-lite/run1/final.cs,artifacts/infer/framework-laptop-13-specs/feedback/google-gemini-2-5-flash-lite/run1/final.cs,artifacts/infer/framework-laptop-13-specs/feedback/google-gemini-2-5-flash-lite/run1/record.json,19,0,[],None
4,framework-laptop-13-specs__feedback__meta-llama-llama-3-2-3b-instruct__run1,framework-laptop-13-specs,feedback,meta-llama/llama-3.2-3b-instruct,framework-laptop-13-specs.md,framework-laptop-13-specs,feedback,meta-llama/llama-3.2-3b-instruct,1,artifacts/infer/framework-laptop-13-specs/feedback/meta-llama-llama-3-2-3b-instruct/run1/final.cs,artifacts/infer/framework-laptop-13-specs/feedback/meta-llama-llama-3-2-3b-instruct/run1/final.cs,artifacts/infer/framework-laptop-13-specs/feedback/meta-llama-llama-3-2-3b-instruct/run1/record.json,25,0,[],None
5,framework-laptop-13-specs__feedback__mistralai-ministral-3b-2512__run1,framework-laptop-13-specs,feedback,mistralai/ministral-3b-2512,framework-laptop-13-specs.md,framework-laptop-13-specs,feedback,mistralai/ministral-3b-2512,1,artifacts/infer/framework-laptop-13-specs/feedback/mistralai-ministral-3b-2512/run1/final.cs,artifacts/infer/framework-laptop-13-specs/feedback/mistralai-ministral-3b-2512/run1/final.cs,artifacts/infer/framework-laptop-13-specs/feedback/mistralai-ministral-3b-2512/run1/record.json,31,0,[],None
6,framework-laptop-13-specs__guided__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,guided,google/gemini-2.5-flash-lite,framework-laptop-13-specs.md,framework-laptop-13-specs,guided,google/gemini-2.5-flash-lite,1,artifacts/infer/framework-laptop-13-specs/guided/google-gemini-2-5-flash-lite/run1/final.cs,artifacts/infer/framework-laptop-13-specs/guided/google-gemini-2-5-flash-lite/run1/final.cs,artifacts/infer/framework-laptop-13-specs/guided/google-gemini-2-5-flash-lite/run1/record.json,37,0,[],None
7,framework-laptop-13-specs__guided__meta-llama-llama-3-2-3b-instruct__run1,framework-laptop-13-specs,guided,meta-llama/llama-3.2-3b-instruct,framework-laptop-13-specs.md,framework-laptop-13-specs,guided,meta-llama/llama-3.2-3b-instruct,1,artifacts/infer/framework-laptop-13-specs/guided/meta-llama-llama-3-2-3b-instruct/run1/final.cs,artifacts/infer/framework-laptop-13-specs/guided/meta-llama-llama-3-2-3b-instruct/run1/final.cs,artifacts/infer/framework-laptop-13-specs/guided/meta-llama-llama-3-2-3b-instruct/run1/record.json,43,0,[],None
8,framework-laptop-13-specs__guided__mistralai-ministral-3b-2512__run1,framework-laptop-13-specs,guided,mistralai/ministral-3b-2512,framework-laptop-13-specs.md,framework-laptop-13-specs,guided,mistralai/ministral-3b-2512,1,artifacts/infer/framework-laptop-13-specs/guided/mistralai-ministral-3b-2512/run1/final.cs,artifacts/infer/framework-laptop-13-specs/guided/mistralai-ministral-3b-2512/run1/final.cs,artifacts/infer/framework-laptop-13-specs/guided/mistralai-ministral-3b-2512/run1/record.json,49,2,"[""/home/bearpro/source/personal/llm-in-lsp-experiment/artifacts/infer/framework-laptop-13-specs/guided/mistralai-ministral-3b-2512/run1/final.cs(107,31): error CS1003: Syntax error, ',' expected"", ""/home/bearpro/source/personal/llm-in-lsp-experiment/artifacts/infer/framework-laptop-13-specs/guided/mistralai-ministral-3b-2512/run1/final.cs(107,48): error CS1001: Identifier expected""]",None
9,github-create-issue-api__control__google-gemini-2-5-flash-lite__run1,github-create-issue-api,control,google/gemini-2.5-flash-lite,github-create-issue-api.md,github-create-issue-api,control,google/gemini-2.5-flash-lite,1,artifacts/infer/github-create-issue-api/control/google-gemini-2-5-flash-lite/run1/final.cs,artifacts/infer/github-create-issue-api/control/google-gemini-2-5-flash-lite/run1/final.cs,artifacts/infer/github-create-issue-api/control/google-gemini-2-5-flash-lite/run1/record.json,2,0,[],None

,model_id,source_document_id,condition,producer_id,element_id,element_kind,symbol_path,parent_symbol_path,name,csharp_type,normalized_type,is_nullable,is_collection,collection_item_type,is_user_defined_type,relation_target_type,comment_text,source_file
0,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0007,enum_member,FrameworkLaptop13.PowerMode.Balanced,FrameworkLaptop13.PowerMode,Balanced,None,enum_member,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
1,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0008,enum_member,FrameworkLaptop13.PowerMode.Efficiency,FrameworkLaptop13.PowerMode,Efficiency,None,enum_member,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
2,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0006,enum_member,FrameworkLaptop13.PowerMode.Performance,FrameworkLaptop13.PowerMode,Performance,None,enum_member,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
3,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0002,enum_member,FrameworkLaptop13.ProcessorOption.RyzenAI5_340,FrameworkLaptop13.ProcessorOption,RyzenAI5_340,None,enum_member,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
4,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0003,enum_member,FrameworkLaptop13.ProcessorOption.RyzenAI7_350,FrameworkLaptop13.ProcessorOption,RyzenAI7_350,None,enum_member,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
5,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0004,enum_member,FrameworkLaptop13.ProcessorOption.RyzenAI9HX_370,FrameworkLaptop13.ProcessorOption,RyzenAI9HX_370,None,enum_member,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
6,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0039,property,FrameworkLaptop13.Dimensions.DepthMM,FrameworkLaptop13.Dimensions,DepthMM,None,number,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
7,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0037,property,FrameworkLaptop13.Dimensions.ThicknessMM,FrameworkLaptop13.Dimensions,ThicknessMM,None,number,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
8,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0038,property,FrameworkLaptop13.Dimensions.WidthMM,FrameworkLaptop13.Dimensions,WidthMM,None,number,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
9,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0043,property,FrameworkLaptop13.Display.AspectRatio,FrameworkLaptop13.Display,AspectRatio,None,string,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
10,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0046,property,FrameworkLaptop13.Display.BrightnessNits,FrameworkLaptop13.Display,BrightnessNits,None,integer,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
11,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0048,property,FrameworkLaptop13.Display.ColorGamut,FrameworkLaptop13.Display,ColorGamut,None,string,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
12,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0041,property,FrameworkLaptop13.Display.Name,FrameworkLaptop13.Display,Name,None,string,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
13,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0047,property,FrameworkLaptop13.Display.RefreshRateHz,FrameworkLaptop13.Display,RefreshRateHz,None,integer,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
14,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0045,property,FrameworkLaptop13.Display.ResolutionHeight,FrameworkLaptop13.Display,ResolutionHeight,None,integer,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
15,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0044,property,FrameworkLaptop13.Display.ResolutionWidth,FrameworkLaptop13.Display,ResolutionWidth,None,integer,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
16,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0042,property,FrameworkLaptop13.Display.SizeInches,FrameworkLaptop13.Display,SizeInches,None,number,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
17,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0049,property,FrameworkLaptop13.Display.Surface,FrameworkLaptop13.Display,Surface,None,string,False,False,NaN,False,NaN,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
18,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0074,property,FrameworkLaptop13.FrameworkLaptop13.Dimensions,FrameworkLaptop13.FrameworkLaptop13,Dimensions,None,user_defined,False,False,NaN,True,Dimensions,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs
19,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1,framework-laptop-13-specs,control,google/gemini-2.5-flash-lite,framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1:e0076,property,FrameworkLaptop13.FrameworkLaptop13.DisplayOptions,FrameworkLaptop13.FrameworkLaptop13,DisplayOptions,None,user_defined,False,True,Display,True,Display,NaN,artifacts/infer/framework-laptop-13-specs/control/google-gemini-2-5-flash-lite/run1/final.cs

In [3]:
sample_model_id = str(model_index.iloc[0]["model_id"])

sample_property_projection = load_projection_csv(
    repo_root,
    "property",
    "path_plus_metadata_values",
    sample_model_id,
)
sample_property_column_map = load_column_map(
    repo_root,
    "property",
    sample_model_id,
)
sample_type_projection = load_projection_csv(
    repo_root,
    "type",
    "members_as_values",
    sample_model_id,
)
sample_relation_projection = load_projection_csv(
    repo_root,
    "relation",
    "path_plus_metadata_values",
    sample_model_id,
)

display({"sample_model_id": sample_model_id})
display(sample_property_projection)
display(JSON(sample_property_column_map, expanded=False))
display(sample_type_projection)
display(sample_relation_projection)

{'sample_model_id': 'framework-laptop-13-specs__control__google-gemini-2-5-flash-lite__run1'}

,FrameworkLaptop13.Dimensions.DepthMM,FrameworkLaptop13.Dimensions.ThicknessMM,FrameworkLaptop13.Dimensions.WidthMM,FrameworkLaptop13.Display.AspectRatio,FrameworkLaptop13.Display.BrightnessNits,FrameworkLaptop13.Display.ColorGamut,FrameworkLaptop13.Display.Name,FrameworkLaptop13.Display.RefreshRateHz,FrameworkLaptop13.Display.ResolutionHeight,FrameworkLaptop13.Display.ResolutionWidth,...,FrameworkLaptop13.Processor.CpuCores,FrameworkLaptop13.Processor.Name,FrameworkLaptop13.Processor.NpuTops,FrameworkLaptop13.Processor.Threads,FrameworkLaptop13.Storage.MaxCapacityTB,FrameworkLaptop13.Storage.Type,FrameworkLaptop13.ThermalSystem.CoolingFan,FrameworkLaptop13.ThermalSystem.HeatPipe,FrameworkLaptop13.ThermalSystem.ThermalInterfaceMaterial,FrameworkLaptop13.WirelessConnectivity.Name
0,name depth mm,name thickness mm,name width mm,name aspect ratio,name brightness nits,name color gamut,name name,name refresh rate hz,name resolution height,name resolution width,...,name cpu cores,name name,name npu tops,name threads,name max capacity tb,name type,name cooling fan,name heat pipe,name thermal interface material,name name
1,parent framework laptop13 dimensions,parent framework laptop13 dimensions,parent framework laptop13 dimensions,parent framework laptop13 display,parent framework laptop13 display,parent framework laptop13 display,parent framework laptop13 display,parent framework laptop13 display,parent framework laptop13 display,parent framework laptop13 display,...,parent framework laptop13 processor,parent framework laptop13 processor,parent framework laptop13 processor,parent framework laptop13 processor,parent framework laptop13 storage,parent framework laptop13 storage,parent framework laptop13 thermal system,parent framework laptop13 thermal system,parent framework laptop13 thermal system,parent framework laptop13 wireless connectivity
2,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,...,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type,csharp type
3,normalized type number,normalized type number,normalized type number,normalized type string,normalized type integer,normalized type string,normalized type string,normalized type integer,normalized type integer,normalized type integer,...,normalized type integer,normalized type string,normalized type integer,normalized type integer,normalized type integer,normalized type string,normalized type string,normalized type string,normalized type string,normalized type string
4,kind property,kind property,kind property,kind property,kind property,kind property,kind property,kind property,kind property,kind property,...,kind property,kind property,kind property,kind property,kind property,kind property,kind property,kind property,kind property,kind property
5,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,...,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single,cardinality single
6,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,...,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan,comment nan
7,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,...,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan,relation target nan

,FrameworkLaptop13.Dimensions,FrameworkLaptop13.Display,FrameworkLaptop13.FrameworkLaptop13,FrameworkLaptop13.Graphics,FrameworkLaptop13.Memory,FrameworkLaptop13.PackageContents,FrameworkLaptop13.PortSystem,FrameworkLaptop13.PowerConfiguration,FrameworkLaptop13.PowerMode,FrameworkLaptop13.Processor,FrameworkLaptop13.ProcessorOption,FrameworkLaptop13.Storage,FrameworkLaptop13.ThermalSystem,FrameworkLaptop13.WirelessConnectivity
0,depth mm,aspect ratio,dimensions,clock speed ghz,max capacity gb,item,expansion card slots,boost processor power watts,balanced,clock speed ghz,ryzen ai5 340,max capacity tb,cooling fan,name
1,thickness mm,brightness nits,display options,cores,speed,NaN,has headphone jack,mode,efficiency,cpu cores,ryzen ai7 350,type,heat pipe,NaN
2,width mm,color gamut,edition,name,type,NaN,NaN,sustained processor power watts,performance,name,ryzen ai9 hx 370,NaN,thermal interface material,NaN
3,NaN,name,integrated graphics,NaN,NaN,NaN,NaN,NaN,NaN,npu tops,NaN,NaN,NaN,NaN
4,NaN,refresh rate hz,is designed for repairability,NaN,NaN,NaN,NaN,NaN,NaN,threads,NaN,NaN,NaN,NaN
5,NaN,resolution height,memory options,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,resolution width,model name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,size inches,package contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,surface,port system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,power configurations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,processor details,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,processor option,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,replacement parts source,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,storage options,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,thermal system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,weight kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,wireless connectivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,relation.FrameworkLaptop13.FrameworkLaptop13.Dimensions.Dimensions,relation.FrameworkLaptop13.FrameworkLaptop13.DisplayOptions.Display,relation.FrameworkLaptop13.FrameworkLaptop13.IntegratedGraphics.Graphics,relation.FrameworkLaptop13.FrameworkLaptop13.MemoryOptions.Memory,relation.FrameworkLaptop13.FrameworkLaptop13.PackageContents.PackageContents,relation.FrameworkLaptop13.FrameworkLaptop13.PortSystem.PortSystem,relation.FrameworkLaptop13.FrameworkLaptop13.PowerConfigurations.PowerConfiguration,relation.FrameworkLaptop13.FrameworkLaptop13.ProcessorDetails.Processor,relation.FrameworkLaptop13.FrameworkLaptop13.StorageOptions.Storage,relation.FrameworkLaptop13.FrameworkLaptop13.ThermalSystem.ThermalSystem,relation.FrameworkLaptop13.FrameworkLaptop13.WirelessConnectivity.WirelessConnectivity
0,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13,source framework laptop13 framework laptop13
1,property dimensions,property display options,property integrated graphics,property memory options,property package contents,property port system,property power configurations,property processor details,property storage options,property thermal system,property wireless connectivity
2,target dimensions,target display,target graphics,target memory,target package contents,target port system,target power configuration,target processor,target storage,target thermal system,target wireless connectivity
3,cardinality single,cardinality many,cardinality single,cardinality single,cardinality many,cardinality single,cardinality many,cardinality single,cardinality single,cardinality single,cardinality single